use nexus_domain::{
    Attachment, AttachmentKind, HarnessKind, Message, MessageKind, MessageRole, RunStatus,
    TaskSummary, ThinkingEffort, ToolMetadata,
};
use nexus_protocol::remote::{RemoteProject, RemoteState, StartRunRequest};
use serde::Serialize;
use uuid::Uuid;

// Serialize real Rust payloads, including omitted fields, rather than a parallel
// JSON schema. TypeScript checks the resulting object literals with `satisfies`.
pub fn typescript() -> String {
    let id = Uuid::nil();
    let mut state = RemoteState {
        projects: vec![RemoteProject {
            id,
            display_name: "Project".into(),
        }],
        tasks: vec![TaskSummary {
            id,
            project_id: Some(id),
            title: "Task".into(),
            status: RunStatus::Running,
            created_at: "2026-01-01T00:00:00Z".parse().unwrap(),
        }],
        selected_project_id: Some(id),
        selected_task_id: Some(id),
        active_run_id: Some(id),
        active_task_id: Some(id),
        streaming_text: "Reply".into(),
        status: "Running".into(),
        harness: HarnessKind::Claude,
        model: Some("model".into()),
        effort: ThinkingEffort::Default,
        harness_ready: true,
    };
    let mut source = String::from(
        "// Generated by `cargo run -p nexus-protocol --example remote_contract`.\n\
         // Checked by both Rust serialization tests and the TypeScript compiler.\n\
         import type { Message, MessageKind, MessageRole, RemoteState, RunStatus, StartRunRequest } from \"./types\";\n\n",
    );
    append(&mut source, "activeState", "RemoteState", &state);
    state.projects.clear();
    state.tasks[0].project_id = None;
    state.selected_project_id = None;
    state.selected_task_id = None;
    state.active_run_id = None;
    state.active_task_id = None;
    state.model = None;
    state.harness_ready = false;
    append(&mut source, "idleState", "RemoteState", &state);

    let mut message = Message {
        id,
        task_id: id,
        run_id: id,
        sequence: 1,
        role: MessageRole::Tool,
        kind: MessageKind::ToolResult,
        content: "Output".into(),
        attachments: vec![
            Attachment {
                path: "/capture.png".into(),
                source_name: "document.pdf".into(),
                page: Some(1),
                kind: AttachmentKind::Image,
            },
            Attachment {
                path: "/file.txt".into(),
                source_name: "file.txt".into(),
                page: None,
                kind: AttachmentKind::File,
            },
        ],
        tool: Some(ToolMetadata {
            id: "tool-1".into(),
            is_error: false,
        }),
        created_at: "2026-01-01T00:00:00Z".parse().unwrap(),
    };
    append(&mut source, "richMessage", "Message", &message);
    message.attachments.clear();
    message.tool = None;
    message.role = MessageRole::User;
    message.kind = MessageKind::Text;
    append(&mut source, "plainMessage", "Message", &message);
    append(
        &mut source,
        "startRun",
        "StartRunRequest",
        &StartRunRequest {
            project_id: id,
            prompt: "Prompt".into(),
        },
    );
    append(
        &mut source,
        "harnesses",
        "RemoteState[\"harness\"][]",
        &HarnessKind::ALL,
    );
    append(
        &mut source,
        "efforts",
        "RemoteState[\"effort\"][]",
        &[
            ThinkingEffort::Default,
            ThinkingEffort::None,
            ThinkingEffort::Off,
            ThinkingEffort::Minimal,
            ThinkingEffort::Low,
            ThinkingEffort::Medium,
            ThinkingEffort::High,
            ThinkingEffort::XHigh,
            ThinkingEffort::Max,
            ThinkingEffort::Ultra,
            ThinkingEffort::Auto,
        ],
    );
    append(
        &mut source,
        "runStatuses",
        "RunStatus[]",
        &[
            RunStatus::Starting,
            RunStatus::Running,
            RunStatus::Cancelling,
            RunStatus::Completed,
            RunStatus::Failed,
            RunStatus::Cancelled,
            RunStatus::Interrupted,
        ],
    );
    append(
        &mut source,
        "messageRoles",
        "MessageRole[]",
        &[
            MessageRole::User,
            MessageRole::Assistant,
            MessageRole::Tool,
            MessageRole::System,
        ],
    );
    append(
        &mut source,
        "messageKinds",
        "MessageKind[]",
        &[
            MessageKind::Text,
            MessageKind::ToolCall,
            MessageKind::ToolResult,
            MessageKind::Status,
            MessageKind::Error,
        ],
    );
    source
}

fn append(source: &mut String, name: &str, kind: &str, value: &impl Serialize) {
    source.push_str(&format!(
        "export const {name} = {} satisfies {kind};\n\n",
        serde_json::to_string_pretty(value).unwrap()
    ));
}
