// Generated by `cargo run -p nexus-protocol --example remote_contract`.
// Checked by both Rust serialization tests and the TypeScript compiler.
import type { Message, MessageKind, MessageRole, RemoteState, RunStatus, StartRunRequest } from "./types";

export const activeState = {
  "projects": [
    {
      "id": "00000000-0000-0000-0000-000000000000",
      "display_name": "Project"
    }
  ],
  "tasks": [
    {
      "id": "00000000-0000-0000-0000-000000000000",
      "project_id": "00000000-0000-0000-0000-000000000000",
      "title": "Task",
      "status": "running",
      "created_at": "2026-01-01T00:00:00Z"
    }
  ],
  "selected_project_id": "00000000-0000-0000-0000-000000000000",
  "selected_task_id": "00000000-0000-0000-0000-000000000000",
  "active_run_id": "00000000-0000-0000-0000-000000000000",
  "active_task_id": "00000000-0000-0000-0000-000000000000",
  "streaming_text": "Reply",
  "status": "Running",
  "harness": "claude",
  "model": "model",
  "effort": "default",
  "harness_ready": true
} satisfies RemoteState;

export const idleState = {
  "projects": [],
  "tasks": [
    {
      "id": "00000000-0000-0000-0000-000000000000",
      "project_id": null,
      "title": "Task",
      "status": "running",
      "created_at": "2026-01-01T00:00:00Z"
    }
  ],
  "selected_project_id": null,
  "selected_task_id": null,
  "active_run_id": null,
  "active_task_id": null,
  "streaming_text": "Reply",
  "status": "Running",
  "harness": "claude",
  "model": null,
  "effort": "default",
  "harness_ready": false
} satisfies RemoteState;

export const richMessage = {
  "id": "00000000-0000-0000-0000-000000000000",
  "task_id": "00000000-0000-0000-0000-000000000000",
  "run_id": "00000000-0000-0000-0000-000000000000",
  "sequence": 1,
  "role": "tool",
  "kind": "tool_result",
  "content": "Output",
  "attachments": [
    {
      "path": "/capture.png",
      "source_name": "document.pdf",
      "page": 1,
      "kind": "image"
    },
    {
      "path": "/file.txt",
      "source_name": "file.txt",
      "kind": "file"
    }
  ],
  "tool": {
    "id": "tool-1",
    "is_error": false
  },
  "created_at": "2026-01-01T00:00:00Z"
} satisfies Message;

export const plainMessage = {
  "id": "00000000-0000-0000-0000-000000000000",
  "task_id": "00000000-0000-0000-0000-000000000000",
  "run_id": "00000000-0000-0000-0000-000000000000",
  "sequence": 1,
  "role": "user",
  "kind": "text",
  "content": "Output",
  "created_at": "2026-01-01T00:00:00Z"
} satisfies Message;

export const startRun = {
  "project_id": "00000000-0000-0000-0000-000000000000",
  "prompt": "Prompt"
} satisfies StartRunRequest;

export const harnesses = [
  "claude",
  "codex",
  "omp",
  "pi",
  "kimi",
  "qoder",
  "qodercn",
  "codebuddy",
  "opencode",
  "deepseek",
  "commandcode"
] satisfies RemoteState["harness"][];

export const efforts = [
  "default",
  "none",
  "off",
  "minimal",
  "low",
  "medium",
  "high",
  "xhigh",
  "max",
  "ultra",
  "auto"
] satisfies RemoteState["effort"][];

export const runStatuses = [
  "starting",
  "running",
  "cancelling",
  "completed",
  "failed",
  "cancelled",
  "interrupted"
] satisfies RunStatus[];

export const messageRoles = [
  "user",
  "assistant",
  "tool",
  "system"
] satisfies MessageRole[];

export const messageKinds = [
  "text",
  "tool_call",
  "tool_result",
  "status",
  "error"
] satisfies MessageKind[];
