use gpui::{App, px, rgb, rgba};
use gpui_component::{Theme, ThemeMode};

pub(super) const SURFACE: u32 = 0x151716;
pub(super) const RECESSED: u32 = 0x272928;
pub(super) const HOVER: u32 = 0x2c2f2d;
pub(super) const SELECTED: u32 = 0x363936;
pub(super) const BORDER: u32 = 0x343735;
pub(super) const TEXT: u32 = 0xf3f5f3;
pub(super) const TEXT_SECONDARY: u32 = 0xc2c6c3;
pub(super) const MUTED: u32 = 0x858b87;
pub(super) const ACCENT: u32 = 0x9b7cff;
pub(super) const ACCENT_HOVER: u32 = 0xad93ff;
pub(super) const LINK: u32 = 0x7aa9ff;
pub(super) const SUCCESS: u32 = 0x51d88a;
pub(super) const WARNING: u32 = 0xffbd66;
pub(super) const DANGER: u32 = 0xff6b70;
pub(super) const TOOL: u32 = 0xe5a65f;

pub(crate) fn configure_theme(cx: &mut App) {
    Theme::change(ThemeMode::Dark, None, cx);
    let theme = Theme::global_mut(cx);
    theme.font_family = ".SystemUIFont".into();
    theme.font_size = px(14.);
    theme.mono_font_family = "SF Mono".into();
    theme.mono_font_size = px(13.);
    theme.radius = px(6.);
    theme.radius_lg = px(12.);
    theme.shadow = false;

    theme.background = rgba(0x101211ee).into();
    theme.foreground = rgb(TEXT).into();
    theme.border = rgb(BORDER).into();
    theme.input = rgba(0xffffff1c).into();
    theme.caret = rgb(TEXT).into();
    theme.ring = rgb(ACCENT).into();
    theme.selection = rgba(0x9b7cff4a).into();
    theme.muted = rgb(RECESSED).into();
    theme.muted_foreground = rgb(MUTED).into();
    theme.accent = rgb(HOVER).into();
    theme.accent_foreground = rgb(TEXT).into();
    theme.primary = rgb(ACCENT).into();
    theme.primary_hover = rgb(ACCENT_HOVER).into();
    theme.primary_active = rgb(0x8968f2).into();
    theme.primary_foreground = rgb(TEXT).into();
    theme.secondary = rgb(RECESSED).into();
    theme.secondary_hover = rgb(HOVER).into();
    theme.secondary_active = rgb(SELECTED).into();
    theme.secondary_foreground = rgb(TEXT_SECONDARY).into();
    theme.link = rgb(LINK).into();
    theme.link_hover = rgb(0x245aa6).into();
    theme.link_active = rgb(0x1e4c8e).into();
    theme.danger = rgb(DANGER).into();
    theme.danger_hover = rgb(0xff8286).into();
    theme.danger_active = rgb(0xe4565c).into();
    theme.danger_foreground = rgb(TEXT).into();
    theme.popover = rgba(0x2a2d2bf2).into();
    theme.popover_foreground = rgb(TEXT).into();
    theme.overlay = rgba(0x00000066).into();
    theme.title_bar = rgba(0x15171600).into();
    theme.title_bar_border = rgba(0xffffff00).into();
    theme.sidebar = rgba(0x1c1e1dde).into();
    theme.sidebar_foreground = rgb(TEXT).into();
    theme.sidebar_accent = rgb(HOVER).into();
    theme.sidebar_accent_foreground = rgb(TEXT).into();
    theme.sidebar_border = rgb(BORDER).into();
}
